name: wifi-ap
version: 16
confinement: strict
summary: WiFi Access Point based on hostapd
description: |
  This snap is implementing a WiFi access point based on hostapd and allows
  easily to share a internet connection or just create a network others can
  easily connect to.
  Please find the source of this snap at:
  https://code.launchpad.net/~snappy-hwe-team/snappy-hwe-snaps/+git/wifi-ap
grade: stable

slots:
  control:
    interface: content
    content: socket-directory
    write:
      - $SNAP_DATA/sockets

apps:
  config:
    command: bin/client config
    plugs:
      - network
  status:
    command: bin/client status
    plugs:
      - network
  setup-wizard:
    command: bin/client wizard
    plugs:
      - network
  management-service:
    command: bin/service
    daemon: simple
    plugs:
      - network-bind
      - network-control
      - firewall-control
      - network-manager
  automatic-setup:
    command: bin/automatic-setup.sh
    daemon: simple
    plugs:
      - network

parts:
  common:
    plugin: dump
    source: .
    prime:
      - copyright.hostapd
      - bin/config-internal.sh
      - bin/ap.sh
      - bin/helper.sh
      - bin/automatic-setup.sh
      - conf/default-config

  network-utils:
    plugin: nil
    stage-packages:
      - iw
      - wireless-tools
    organize:
      sbin: bin
    filesets:
      binaries:
        - bin/iw
        - bin/iwconfig
    prime:
      - $binaries

  service:
    plugin: go
    source: .
    go-importpath: launchpad.net/wifi-ap
    prime:
      - bin
    install: |
      export GOPATH=$PWD/../go
      for d in client service ; do
        cd $GOPATH/src/launchpad.net/wifi-ap/cmd/$d
        go test -v
      done

  dnsmasq:
    plugin: make
    source: https://git.launchpad.net/~snappy-hwe-team/snappy-hwe-snaps/+git/wifi-ap
    source-type: git
    source-branch: dnsmasq/2.75
    build-packages:
      - build-essential
    make-parameters:
      - PREFIX=/
    organize:
      sbin/dnsmasq: bin/dnsmasq
    filesets:
      binaries:
        - bin/dnsmasq
    prime:
      - $binaries

  hostapd:
    plugin: make
    source: https://git.launchpad.net/~snappy-hwe-team/snappy-hwe-snaps/+git/wifi-ap
    source-type: git
    source-branch: hostapd/2.5
    build-packages:
      - build-essential
      - pkg-config
      - libnl-3-dev
      - libnl-genl-3-dev
      - libnl-route-3-dev
      - libssl-dev
    make-parameters:
      - BINDIR=/bin
    filesets:
      binaries:
        - bin/hostapd
        - bin/hostapd_cli
    prime:
      - $binaries

  hostapd-rtl8188:
    plugin: make
    source: https://git.launchpad.net/~snappy-hwe-team/snappy-hwe-snaps/+git/wifi-ap
    source-type: git
    source-branch: hostapd/2.5-rtl8188
    build-packages:
      - build-essential
      - pkg-config
      - libnl-3-dev
      - libnl-genl-3-dev
      - libnl-route-3-dev
      - libssl-dev
    make-parameters:
      - BINDIR=/rtl8188
    filesets:
      binaries:
        - rtl8188/hostapd
    prime:
      - $binaries

  nmcli:
    plugin: nil
    stage-packages:
      - network-manager
    organize:
      usr/bin/nmcli: bin/nmcli
