#!/bin/bash
#
# Copyright (C) 2015, 2016 Canonical Ltd
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

DISABLED=1

# Set to '1' for verbose debugging
DEBUG=0

# Default configuration
WIFI_INTERFACE=wlan0
WIFI_ADDRESS=192.168.7.1

# Possible options are: uap, direct
#   virtual:
#     Creates a virtual network interface for the AP with
#     the interface configured in $WIFI_INTERFACE as parent.
#   direct:
#     Will use the interface configured with $WIFI_INTERFACE
#     directly.
WIFI_INTERFACE_MODE=virtual

# Possible options are: nl80211, rtl8188
WIFI_HOSTAPD_DRIVER="nl80211"

WIFI_SSID="Ubuntu"

# Can be 'open' or 'wpa2'
WIFI_SECURITY="open"
# WIFI_SECURITY="wpa2"
# WIFI_SECURITY_PASSPHRASE="Ubuntu16.04"

WIFI_CHANNEL=6
# Operation mode (a = IEEE 802.11a (5 GHz), b = IEEE 802.11b (2.4 GHz),
# g = IEEE 802.11g (2.4 GHz), ad = IEEE 802.11ad (60 GHz);
WIFI_OPERATION_MODE="g"

# Network interface which connection will be shared with connected
# clients. Set to 'none' for not shared network connection.
SHARE_NETWORK_INTERFACE=eth0

DHCP_RANGE_START=192.168.7.5
DHCP_RANGE_STOP=192.168.7.100
DHCP_LEASE_TIME="12h"

